name: banana-split
version: 0.1.0.0

dependencies:
  - base
  - aeson
  - bytestring
  - conferer
  - containers
  - digestive-functors
  - glpk-hs
  - hmatrix
  - hmatrix-glpk
  - http-api-data
  - http-media
  - lucid2
  - lucid2-htmx
  - mtl
  # - optics
  - postgresql-migration
  - pretty-simple
  - random
  - resource-pool
  - safe-money
  - safe-money-aeson
  - selda
  - selda-postgresql
  - servant
  - servant-elm
  - elm-bridge
  - servant-htmx
  - servant-server
  - string-conversions
  - string-interpolate
  - text
  - time
  - ulid
  - unix
  - unordered-containers
  - wai
  - wai-extra
  - wai-app-static
  - file-embed
  - warp

language: GHC2021

default-extensions:
  - OverloadedStrings
  - LambdaCase

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  banana-split:
    source-dirs: app
    main: Main.hs
    dependencies:
      - banana-split
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - banana-split
      - hspec
      - QuickCheck
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
