services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      source:
        type: lexical
        pattern: '^$slug-\d{8}-\d{6}$'
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: $slug.split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
