services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      tag: 20260831-055628@sha256:b4a85c98e31450ca6cb19c5e4b11fdaeb79ddb338416ffa1f1a13e1a5e0542c4
      source:
        type: lexical
        pattern: '^\d{8}-\d{6}$'
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: dev.split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
