services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      tag: 20260305-022203@sha256:9a3437f421392f0addfd35b1ad043cc7622a0193302e86911d2bb5fb1f8e9365
      source:
        type: upstream
        stage: dev
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: stg.split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
