services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      tag: 20260307-220818@sha256:198052a9f6939aec6dd1308e66320fe7807545ca44774aaa0d05d75aa2031603
      source:
        type: upstream
        stage: dev
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: stg.split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
