services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      tag: 20260916-080131@sha256:1acad3542607239295bb207b8e1d3ad886e8367cefa4cdbf10f94331717fd5f2
      source:
        type: upstream
        stage: dev
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: stg.split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
