database.url=postgres://postgres:postgres@127.0.0.1/bananasplit_dev
openrouter.apikey=lele
openrouter.models.0=lele

auth.jwtsecret=dev-insecure-secret-change-me-please-32-bytes-min
auth.securecookie=false

mailer.type=smtp
mailer.smtp.host=localhost
mailer.smtp.from=banana-split@ludat.io
mailer.smtp.port=1025
mailer.smtp.security=plain
