production: true
services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      tag: 20260629-044547@sha256:2737b14da3658685f3f927bf82571c3e2934b8cfb84d062bd957642afe966d32
      source:
        type: upstream
        stage: stg
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
