production: true
services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      tag: 20260529-023921@sha256:7caa66e49db38e0bdef6080cd04d1a788c632ec898851de09e2f955d36ed2c41
      source:
        type: upstream
        stage: stg
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
