production: true
services:
  backend:
    image:
      repository: ghcr.io/ludat/banana-split
      tag: 20260722-191540@sha256:1d6db5fe37c5f0b3156c254379decac41563e36ac3b0a0029c09882b66bc0bb2
      source:
        type: upstream
        stage: stg
    port: 8000
    secrets:
      - config
    dependencies: [pg]
    routes:
      - host: split.ludat.io

dependencies:
  pg:
    type: postgres

hooks:
  pre-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            timeout 10 banana-split migrations init
            banana-split migrations migrate ./migrations
  post-deploy:
    - name: migrations
      service: backend
      command:
        - sh
        - -c
        - |
            if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
              banana-split migrations complete
            fi
