name: "Build docker image"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - run: nix build .#docker --option sandbox relaxed -L

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to ghcr
      if: github.ref == 'refs/heads/main'
      run: |
        docker load < result
        docker tag banana-split ghcr.io/ludat/banana-split:latest
        docker push ghcr.io/ludat/banana-split:latest
        docker tag banana-split ghcr.io/ludat/banana-split:${{ github.sha }}
        docker push ghcr.io/ludat/banana-split:${{ github.sha }}

    - name: Trigger infra-cluster deploy
      # https://gitlab.com/10Pines/infra/infra-cluster
      # Infra cluster project id = 32472203
      if: github.ref == 'refs/heads/main'
      run: |
        curl --request POST \
          --form "variables[ENV]=prod" \
          --form "variables[APP]=banana-split" \
          --form "variables[HELM_VALUES]=revision: '${{ github.sha }}'" \
          "https://gitlab.com/api/v4/projects/32472203/trigger/pipeline?token=${{ secrets.GITLAB_INFRA_TOKEN }}&ref=main"
