name: "Build docker image"
on:
  push:
  release:
    types: [released]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Build everything
      run: |
        nix build

    - name: Build docker image
      run: nix build .#docker --option sandbox relaxed -L
      if: github.ref == 'refs/heads/main'

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image to ghcr
      if: github.ref == 'refs/heads/main'
      run: |
        docker load < result

        docker tag banana-split ghcr.io/ludat/banana-split:${{ github.sha }}
        docker push ghcr.io/ludat/banana-split:${{ github.sha }}

        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker tag banana-split ghcr.io/ludat/banana-split:latest
          docker push ghcr.io/ludat/banana-split:latest
        fi

        if [ "${{ github.event_name }}" = "release" ]; then
          docker tag banana-split ghcr.io/ludat/banana-split:${{ github.event.release.tag_name }}
          docker push ghcr.io/ludat/banana-split:${{ github.event.release.tag_name }}
        fi

    - name: Trigger infra-cluster deploy
      # https://gitlab.com/10Pines/infra/infra-cluster
      # Infra cluster project id = 32472203
      if: github.ref == 'refs/heads/main'
      run: |
        curl --request POST \
          --form "variables[ENV]=prod" \
          --form "variables[APP]=banana-split" \
          --form "variables[HELM_VALUES]=revision: '${{ github.sha }}'" \
          "https://gitlab.com/api/v4/projects/32472203/trigger/pipeline?token=${{ secrets.GITLAB_INFRA_TOKEN }}&ref=main"
