name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "charts/**"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve version from Chart.yaml
        id: chart_version
        run: |
          echo "version=$(yq '.version' charts/banana-split/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login -u ${{ github.actor }} --password-stdin ghcr.io

      - name: Push Chart to GHCR (${{ steps.chart_version.outputs.version }})
        run: |
          set -euo pipefail
          set -x
          if helm pull oci://ghcr.io/ludat/charts/banana-split --version ${{ steps.chart_version.outputs.version }}; then
            echo "Version ${{ steps.chart_version.outputs.version }} exists."
            echo "Failing."
            exit 1
          fi

          helm package charts/banana-split

          helm push "banana-split-${{ steps.chart_version.outputs.version }}.tgz" oci://ghcr.io/ludat/charts
