apiVersion: v1
kind: Service
metadata:
  name: {{ include "banana-split.fullname" . }}
  labels:
    {{- include "banana-split.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "banana-split.selectorLabels" . | nindent 4 }}
